# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commit',
            new_name='Comment',
        ),
    ]
